version: "3.8"

services:
  app:
    build: .
    image: ${IMAGE_NAME:-saswati26/verbalize}:${IMAGE_TAG:-latest}
    container_name: verbalize-app
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
